[[multichain]]
chainID = 43113
name = "Avalanche Testnet"
gateway = "https://rpc.ankr.com/avalanche"
cbridge = "0xe95E3a9f1a45B5EDa71781448F6047d7B7e31cbF"
msgbus = "0xE9533976C590200E32d95C53f06AE12d292cFc47"
blkinterval = 5
blkdelay = 8
maxblkdelta = 5000
addgasestimateratio = 0.1 # multiply gas limit by this ratio

[[multichain]]
chainID = 97
name = "BSC Testnet"
gateway = "https://data-seed-prebsc-2-s3.binance.org:8545/"
cbridge = "0xf89354F314faF344Abd754924438bA798E306DF2"
msgbus = "0xAd204986D6cB67A5Bc76a3CB8974823F43Cb9AAA"
blkinterval = 5
blkdelay = 8
maxblkdelta = 5000
addgasestimateratio = 0.1 # multiply gas limit by this ratio

[[multichain]]
chainID = 4002
name = "Fantom Testnet"
gateway = "https://rpc.testnet.fantom.network"
cbridge = "0xFA78cBa4ebbf8fE28B4fC1468948F16Fda2752b3"
msgbus = "0xb92d6933A024bcca9A21669a480C236Cbc973110"
blkinterval = 5
blkdelay = 8
maxblkdelta = 5000
addgasestimateratio = 0.1 # multiply gas limit by this ratio

[[multichain]]
chainID =
name = "Polygon Mumbai"
gateway = "https://rpc-mainnet.maticvigil.com/"
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
msgbus = "0x7d43AABC515C356145049227CeE54B608342c0ad"
blkinterval = 5
blkdelay = 8
maxblkdelta = 5000
addgasestimateratio = 0.1 # multiply gas limit by this ratio
